<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Bitacoras [
    <!ELEMENT Bitacoras (Bitacora*)>
    <!ATTLIST Bitacora BitacoraId ID #REQUIRED>
    <!ELEMENT Bitacora (Fecha, EmpleadoId, Evento)>
    <!ELEMENT Fecha (#PCDATA)>
    <!ELEMENT EmpleadoId (#PCDATA)>
    <!ELEMENT Evento (#PCDATA)>
]>
<Bitacoras>
  <Bitacora BitacoraId="1">
    <Fecha>23/2/2024 17:16:05</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="2">
    <Fecha>23/2/2024 17:16:07</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>BACKUP DEL SISTEMA</Evento>
  </Bitacora>
  <Bitacora BitacoraId="3">
    <Fecha>23/2/2024 17:17:27</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="4">
    <Fecha>23/2/2024 17:20:28</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="5">
    <Fecha>23/2/2024 17:23:26</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="6">
    <Fecha>23/2/2024 17:24:07</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="7">
    <Fecha>23/2/2024 17:25:02</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="8">
    <Fecha>23/2/2024 17:25:14</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Restore Backup 23/2/2024 17:16:07</Evento>
  </Bitacora>
  <Bitacora BitacoraId="9">
    <Fecha>23/2/2024 17:25:32</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (pepin)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="10">
    <Fecha>23/2/2024 17:25:42</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Restore Backup 23/2/2024 17:16:07</Evento>
  </Bitacora>
  <Bitacora BitacoraId="11">
    <Fecha>23/2/2024 17:27:16</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="12">
    <Fecha>23/2/2024 17:27:48</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Cliente eliminado (Marcos Nahuel Borger)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="13">
    <Fecha>23/2/2024 17:28:54</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="14">
    <Fecha>23/2/2024 17:29:03</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Restore Backup 23/2/2024 17:16:07</Evento>
  </Bitacora>
  <Bitacora BitacoraId="15">
    <Fecha>24/2/2024 16:27:57</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="16">
    <Fecha>24/2/2024 16:28:56</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (carlos1)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="17">
    <Fecha>24/2/2024 16:29:04</Fecha>
    <EmpleadoId>6</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="18">
    <Fecha>24/2/2024 16:29:13</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="19">
    <Fecha>24/2/2024 16:30:10</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="20">
    <Fecha>24/2/2024 16:40:41</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="21">
    <Fecha>24/2/2024 16:41:07</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Cliente eliminado (Marcos Nahuel Borger)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="22">
    <Fecha>24/2/2024 16:41:26</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Restore Backup 23/2/2024 17:16:07</Evento>
  </Bitacora>
  <Bitacora BitacoraId="23">
    <Fecha>24/2/2024 16:42:36</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="24">
    <Fecha>24/2/2024 16:44:10</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="25">
    <Fecha>24/2/2024 16:44:57</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="26">
    <Fecha>24/2/2024 16:45:11</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Cliente eliminado (Marcos Nahuel Borger)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="27">
    <Fecha>24/2/2024 16:45:30</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Restore Backup 23/2/2024 17:16:07</Evento>
  </Bitacora>
  <Bitacora BitacoraId="28">
    <Fecha>24/2/2024 16:45:32</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Restore Backup 23/2/2024 17:16:07</Evento>
  </Bitacora>
  <Bitacora BitacoraId="29">
    <Fecha>24/2/2024 16:45:54</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="30">
    <Fecha>24/2/2024 16:47:37</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="31">
    <Fecha>24/2/2024 16:51:41</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="32">
    <Fecha>24/2/2024 16:52:27</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Permiso Operario retirado al usuario Marcos</Evento>
  </Bitacora>
  <Bitacora BitacoraId="33">
    <Fecha>24/2/2024 16:52:28</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Permiso Despachador retirado al usuario Marcos</Evento>
  </Bitacora>
  <Bitacora BitacoraId="34">
    <Fecha>24/2/2024 16:52:29</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Rol Vendedor asignado al usuario Marcos</Evento>
  </Bitacora>
  <Bitacora BitacoraId="35">
    <Fecha>24/2/2024 16:54:12</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="36">
    <Fecha>24/2/2024 16:54:33</Fecha>
    <EmpleadoId>2</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="37">
    <Fecha>24/2/2024 16:56:34</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="38">
    <Fecha>24/2/2024 16:57:48</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Orden de produccion N°1 generada</Evento>
  </Bitacora>
  <Bitacora BitacoraId="39">
    <Fecha>24/2/2024 16:59:33</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="40">
    <Fecha>24/2/2024 17:01:03</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="41">
    <Fecha>24/2/2024 17:01:41</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="42">
    <Fecha>24/2/2024 17:05:40</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="43">
    <Fecha>24/2/2024 17:07:26</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="44">
    <Fecha>24/2/2024 17:10:39</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="45">
    <Fecha>24/2/2024 17:12:15</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Nuevo pedido N° registrado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="46">
    <Fecha>24/2/2024 17:12:39</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Orden de produccion N°2 generada</Evento>
  </Bitacora>
  <Bitacora BitacoraId="47">
    <Fecha>24/2/2024 17:14:28</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="48">
    <Fecha>24/2/2024 17:15:58</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="49">
    <Fecha>24/2/2024 17:16:44</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Pedido de material N°1 finalizado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="50">
    <Fecha>24/2/2024 17:18:41</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="51">
    <Fecha>24/2/2024 17:19:05</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (carlos)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="52">
    <Fecha>24/2/2024 17:19:36</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (carlos)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="53">
    <Fecha>24/2/2024 17:19:57</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (carlos)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="54">
    <Fecha>24/2/2024 17:20:06</Fecha>
    <EmpleadoId>3</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="55">
    <Fecha>24/2/2024 17:20:30</Fecha>
    <EmpleadoId>3</EmpleadoId>
    <Evento>Orden de produccion finalizada N°1</Evento>
  </Bitacora>
  <Bitacora BitacoraId="56">
    <Fecha>24/2/2024 17:20:42</Fecha>
    <EmpleadoId>3</EmpleadoId>
    <Evento>Orden de produccion finalizada N°2</Evento>
  </Bitacora>
  <Bitacora BitacoraId="57">
    <Fecha>24/2/2024 17:22:48</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="58">
    <Fecha>24/2/2024 17:23:17</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (prueba)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="59">
    <Fecha>24/2/2024 17:23:33</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>BACKUP DEL SISTEMA</Evento>
  </Bitacora>
  <Bitacora BitacoraId="60">
    <Fecha>24/2/2024 17:24:07</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (prueba)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="61">
    <Fecha>24/2/2024 17:24:20</Fecha>
    <EmpleadoId>6</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="62">
    <Fecha>24/2/2024 17:24:31</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="63">
    <Fecha>24/2/2024 17:24:41</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Rol Administrador del sistema asignado al usuario prueba</Evento>
  </Bitacora>
  <Bitacora BitacoraId="64">
    <Fecha>24/2/2024 17:24:53</Fecha>
    <EmpleadoId>6</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="65">
    <Fecha>24/2/2024 17:25:03</Fecha>
    <EmpleadoId>6</EmpleadoId>
    <Evento>Restore Backup 24/2/2024 17:23:33</Evento>
  </Bitacora>
  <Bitacora BitacoraId="66">
    <Fecha>24/2/2024 17:25:56</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="67">
    <Fecha>24/2/2024 17:35:05</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="68">
    <Fecha>24/2/2024 17:35:11</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>BACKUP DEL SISTEMA</Evento>
  </Bitacora>
  <Bitacora BitacoraId="69">
    <Fecha>24/2/2024 17:37:29</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="70">
    <Fecha>24/2/2024 17:37:40</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>BACKUP DEL SISTEMA</Evento>
  </Bitacora>
  <Bitacora BitacoraId="71">
    <Fecha>24/2/2024 17:38:30</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Restore Backup 24/2/2024 17:37:40</Evento>
  </Bitacora>
  <Bitacora BitacoraId="72">
    <Fecha>27/2/2024 16:03:41</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="73">
    <Fecha>27/2/2024 16:05:33</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="74">
    <Fecha>27/2/2024 16:06:58</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="75">
    <Fecha>27/2/2024 16:07:19</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (josegomez)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="76">
    <Fecha>27/2/2024 16:09:02</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="77">
    <Fecha>27/2/2024 16:21:31</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="78">
    <Fecha>27/2/2024 16:21:53</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (prueba)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="79">
    <Fecha>27/2/2024 16:22:28</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (prueba1)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="80">
    <Fecha>27/2/2024 16:22:46</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (prueba1)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="81">
    <Fecha>27/2/2024 16:24:05</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="82">
    <Fecha>27/2/2024 16:24:21</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (prueba1)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="83">
    <Fecha>27/2/2024 16:24:21</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Cambio de nombre de usuario (prueba -&gt; prueba1)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="84">
    <Fecha>27/2/2024 16:24:26</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (prueba1)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="85">
    <Fecha>27/2/2024 16:24:37</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (prueba1)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="86">
    <Fecha>27/2/2024 16:26:03</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="87">
    <Fecha>27/2/2024 16:26:47</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="88">
    <Fecha>27/2/2024 16:26:54</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (josegomez)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="89">
    <Fecha>27/2/2024 16:27:08</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (Marcos)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="90">
    <Fecha>27/2/2024 16:27:34</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (prueba)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="91">
    <Fecha>27/2/2024 16:27:50</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (prueba1)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="92">
    <Fecha>27/2/2024 16:27:50</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Cambio de nombre de usuario (prueba -&gt; prueba1)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="93">
    <Fecha>27/2/2024 16:28:59</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="94">
    <Fecha>27/2/2024 16:29:43</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (prueba)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="95">
    <Fecha>27/2/2024 16:29:53</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (prueba)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="96">
    <Fecha>27/2/2024 16:30:28</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="97">
    <Fecha>27/2/2024 16:30:48</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (prueba)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="98">
    <Fecha>27/2/2024 16:32:35</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="99">
    <Fecha>27/2/2024 16:33:18</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="100">
    <Fecha>27/2/2024 16:33:35</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (prueba)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="101">
    <Fecha>27/2/2024 16:59:55</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="102">
    <Fecha>27/2/2024 17:01:38</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Nuevo pedido N° registrado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="103">
    <Fecha>28/2/2024 16:38:30</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="104">
    <Fecha>28/2/2024 16:40:21</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="105">
    <Fecha>28/2/2024 16:41:04</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (josegomez)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="106">
    <Fecha>28/2/2024 16:41:12</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (josegomez)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="107">
    <Fecha>28/2/2024 16:43:17</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="108">
    <Fecha>28/2/2024 16:43:48</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="109">
    <Fecha>28/2/2024 16:45:14</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="110">
    <Fecha>28/2/2024 16:50:38</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="111">
    <Fecha>28/2/2024 16:50:53</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (nuevo)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="112">
    <Fecha>28/2/2024 16:51:01</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Rol Administrador del sistema asignado al usuario nuevo</Evento>
  </Bitacora>
  <Bitacora BitacoraId="113">
    <Fecha>28/2/2024 16:51:09</Fecha>
    <EmpleadoId>7</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="114">
    <Fecha>29/2/2024 16:52:14</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="115">
    <Fecha>29/2/2024 17:07:33</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="116">
    <Fecha>29/2/2024 17:07:57</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="117">
    <Fecha>29/2/2024 17:10:03</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="118">
    <Fecha>29/2/2024 17:13:55</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="119">
    <Fecha>29/2/2024 17:14:25</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (nuevo)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="120">
    <Fecha>29/2/2024 17:14:32</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Rol Vendedor asignado al usuario nuevo</Evento>
  </Bitacora>
  <Bitacora BitacoraId="121">
    <Fecha>29/2/2024 17:14:39</Fecha>
    <EmpleadoId>7</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="122">
    <Fecha>29/2/2024 17:17:52</Fecha>
    <EmpleadoId>7</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="123">
    <Fecha>29/2/2024 17:18:58</Fecha>
    <EmpleadoId>7</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="124">
    <Fecha>29/2/2024 17:19:11</Fecha>
    <EmpleadoId>7</EmpleadoId>
    <Evento>Cliente modificado (Lucas Muñoz)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="125">
    <Fecha>29/2/2024 17:20:15</Fecha>
    <EmpleadoId>7</EmpleadoId>
    <Evento>Nuevo cliente registrado (Jose Gutierrez)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="126">
    <Fecha>29/2/2024 17:20:18</Fecha>
    <EmpleadoId>7</EmpleadoId>
    <Evento>Cliente eliminado (Jose Gutierrez)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="127">
    <Fecha>29/2/2024 17:21:05</Fecha>
    <EmpleadoId>7</EmpleadoId>
    <Evento>Nuevo pedido N° registrado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="128">
    <Fecha>29/2/2024 17:22:28</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="129">
    <Fecha>29/2/2024 17:22:46</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Nuevo pedido N° registrado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="130">
    <Fecha>29/2/2024 17:29:48</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="131">
    <Fecha>29/2/2024 17:30:36</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se genero la orden de entrega N°6</Evento>
  </Bitacora>
  <Bitacora BitacoraId="132">
    <Fecha>29/2/2024 17:30:59</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Orden de entrega n°6 cumplida</Evento>
  </Bitacora>
  <Bitacora BitacoraId="133">
    <Fecha>29/2/2024 17:31:48</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Orden de produccion N°1 generada</Evento>
  </Bitacora>
  <Bitacora BitacoraId="134">
    <Fecha>29/2/2024 17:32:11</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="135">
    <Fecha>29/2/2024 17:33:13</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Pedido de material N°1 finalizado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="136">
    <Fecha>29/2/2024 17:35:25</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="137">
    <Fecha>29/2/2024 17:37:46</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (josegomez)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="138">
    <Fecha>29/2/2024 17:38:30</Fecha>
    <EmpleadoId>5</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="139">
    <Fecha>29/2/2024 17:38:46</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="140">
    <Fecha>29/2/2024 17:39:08</Fecha>
    <EmpleadoId>3</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="141">
    <Fecha>29/2/2024 17:39:16</Fecha>
    <EmpleadoId>3</EmpleadoId>
    <Evento>Orden de produccion finalizada N°1</Evento>
  </Bitacora>
  <Bitacora BitacoraId="142">
    <Fecha>29/2/2024 17:39:28</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="143">
    <Fecha>29/2/2024 17:41:53</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="144">
    <Fecha>29/2/2024 17:42:57</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="145">
    <Fecha>29/2/2024 17:43:28</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (nuevo)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="146">
    <Fecha>29/2/2024 17:43:42</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (hola)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="147">
    <Fecha>3/3/2024 18:16:16</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="148">
    <Fecha>3/3/2024 18:17:58</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Nuevo pedido N° registrado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="149">
    <Fecha>3/3/2024 18:20:53</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se genero la orden de entrega N°7</Evento>
  </Bitacora>
  <Bitacora BitacoraId="150">
    <Fecha>3/3/2024 18:21:31</Fecha>
    <EmpleadoId>5</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="151">
    <Fecha>3/3/2024 18:22:21</Fecha>
    <EmpleadoId>5</EmpleadoId>
    <Evento>Orden de entrega n°7 cumplida</Evento>
  </Bitacora>
  <Bitacora BitacoraId="152">
    <Fecha>3/3/2024 18:22:28</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="153">
    <Fecha>3/3/2024 18:23:12</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Modifico al usuario (jefe)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="154">
    <Fecha>3/3/2024 18:23:12</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Cambio de nombre de usuario (nuevo -&gt; jefe)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="155">
    <Fecha>3/3/2024 18:23:18</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Permiso Vendedor retirado al usuario jefe</Evento>
  </Bitacora>
  <Bitacora BitacoraId="156">
    <Fecha>3/3/2024 18:23:19</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Rol Jefe de planta asignado al usuario jefe</Evento>
  </Bitacora>
  <Bitacora BitacoraId="157">
    <Fecha>3/3/2024 18:23:35</Fecha>
    <EmpleadoId>7</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="158">
    <Fecha>3/3/2024 18:24:31</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="159">
    <Fecha>3/3/2024 18:24:44</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Nuevo pedido N° registrado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="160">
    <Fecha>3/3/2024 18:25:11</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Orden de produccion N°1 generada</Evento>
  </Bitacora>
  <Bitacora BitacoraId="161">
    <Fecha>3/3/2024 18:25:21</Fecha>
    <EmpleadoId>7</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="162">
    <Fecha>3/3/2024 18:27:28</Fecha>
    <EmpleadoId>7</EmpleadoId>
    <Evento>Pedido de material N°1 finalizado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="163">
    <Fecha>3/3/2024 18:29:06</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="164">
    <Fecha>3/3/2024 18:29:34</Fecha>
    <EmpleadoId>3</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="165">
    <Fecha>3/3/2024 18:30:18</Fecha>
    <EmpleadoId>3</EmpleadoId>
    <Evento>Orden de produccion finalizada N°1</Evento>
  </Bitacora>
  <Bitacora BitacoraId="166">
    <Fecha>3/3/2024 18:30:26</Fecha>
    <EmpleadoId>7</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="167">
    <Fecha>4/3/2024 16:56:42</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="168">
    <Fecha>4/3/2024 16:57:21</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Registró un nuevo usuario (Profesor)</Evento>
  </Bitacora>
  <Bitacora BitacoraId="169">
    <Fecha>4/3/2024 16:57:44</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Rol Administrador del sistema asignado al usuario Profesor</Evento>
  </Bitacora>
  <Bitacora BitacoraId="170">
    <Fecha>4/3/2024 16:57:54</Fecha>
    <EmpleadoId>8</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="171">
    <Fecha>4/3/2024 16:58:27</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Se ha loggeado</Evento>
  </Bitacora>
  <Bitacora BitacoraId="172">
    <Fecha>4/3/2024 16:58:49</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Permiso Generar orden de entrega retirado al usuario Profesor</Evento>
  </Bitacora>
  <Bitacora BitacoraId="173">
    <Fecha>4/3/2024 16:58:50</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Permiso Generar orden de entrega retirado al usuario Profesor</Evento>
  </Bitacora>
  <Bitacora BitacoraId="174">
    <Fecha>4/3/2024 16:58:51</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Permiso Administrador del sistema retirado al usuario Profesor</Evento>
  </Bitacora>
  <Bitacora BitacoraId="175">
    <Fecha>4/3/2024 16:58:52</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Rol Administrador del sistema asignado al usuario Profesor</Evento>
  </Bitacora>
  <Bitacora BitacoraId="176">
    <Fecha>4/3/2024 16:58:59</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Permiso Generar orden de entrega retirado al usuario Profesor</Evento>
  </Bitacora>
  <Bitacora BitacoraId="177">
    <Fecha>4/3/2024 16:59:00</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Permiso Generar orden de entrega retirado al usuario Profesor</Evento>
  </Bitacora>
  <Bitacora BitacoraId="178">
    <Fecha>4/3/2024 16:59:03</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Permiso Cumplir orden de entrega asignado al usuario Profesor</Evento>
  </Bitacora>
  <Bitacora BitacoraId="179">
    <Fecha>4/3/2024 16:59:03</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Permiso Cumplir orden de entrega retirado al usuario Profesor</Evento>
  </Bitacora>
  <Bitacora BitacoraId="180">
    <Fecha>4/3/2024 16:59:07</Fecha>
    <EmpleadoId>1</EmpleadoId>
    <Evento>Permiso Tomar pedido retirado al usuario Profesor</Evento>
  </Bitacora>
  <Bitacora BitacoraId="181">
    <Fecha>4/3/2024 16:59:20</Fecha>
    <EmpleadoId>1</EmpleadoId>